name: psp-cancer-py
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - libffi=3.2.1
  - matplotlib=3.1.3 
  - numpy=1.18.1
  - pandas=1.0.3
  - pytables=3.6.1
  - python=3.7.7
  - python.app=2
  - seaborn=0.10.0
  - scikit-learn=0.22.1
  - spyder=4.1.2
  - statsmodels=0.11.0
  - toml=0.10.0
  - xgboost=1.0.2
 

